annotations:
  truecharts.org/SCALE-support: "true"
  truecharts.org/catagories: |
    - media
  truecharts.org/grade: U
apiVersion: v2
appVersion: 1.30.1
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 11.1.2
description: Bridges events and allows you to control your Zigbee devices via MQTT
home: https://truecharts.org/charts/stable/zigbee2mqtt
icon: https://truecharts.org/img/hotlink-ok/chart-icons/zigbee2mqtt.png
keywords:
- zigbee
- mqtt
- home-assistant
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: zigbee2mqtt
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/zigbee2mqtt
- https://hub.docker.com/r/koenkk/zigbee2mqtt
- https://github.com/Koenkk/zigbee2mqtt
version: 6.0.15
